### ISSUE TITLE
Inception Fixes

### ISSUE THREAD

**Issue by harshkumbhani** [itseugen/Inception#1]
# NGINX

1. Maybe use **openssl command** in dockerfile to dynamically generate **certificates** rather than a static one
2. In nginx.conf file, use correct path to the certificates as shown below: ( Not 100% sure but it always worked for me with the later paths to certificates, You can try and let me know)
Previous version:
```
                ssl_certificate /etc/nginx/certs/server.crt;
		ssl_certificate_key /etc/nginx/certs/server.key;
```
Change to
```
                ssl_certificate /etc/ssl/certs/server.crt;
		ssl_certificate_key /etc/ssl/private/server.key
```

# Wordpress
## WWW.CONF
- Remove all the comments and empty / new lines

## INIT.SH
- Nothing much to change except removing `cd /var/www/html` command and `wp core download --allow-root`
- I would recommend to move `wp core download` to `dockerfile` instead of the init script and `use --path option`

## Dockerfile

```
FROM debian:12

WORKDIR /var/www/html

RUN apt-get update \
	&& apt install -y php php8.2-fpm php8.2-mysqli wget \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /var/www/html /run/php

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
		chmod +x wp-cli.phar && \
		mv wp-cli.phar /usr/local/bin/wp && \
		wp core download --path=/var/www/html --version=6.5.2 --allow-root

COPY www.conf /etc/php/8.2/fpm/pool.d/www.conf

COPY init.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init.sh

RUN chown -R www-data:www-data /var/www/
RUN chown www-data:www-data /var/log/
RUN chown -R www-data:www-data /run/php

USER www-data

EXPOSE 9000

CMD ["/usr/local/bin/init.sh"]
```

**Comment by itseugen** [comment]
Thanks. Implemented and fixed! <3
